{% set name = "python-keycloak" %}
{% set version = "2.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1e30cb26cd30163515e0a60338a14969053fe904279159a39b5442bd8dcb1d75

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4
    - poetry-core >=1.0.0
  run:
    - python >=3.7,<4
    - python-jose >=3.3.0
    - requests >=2.20.0
    - requests-toolbelt >=0.9.1
    - urllib3 >=1.26.0

test:
  requires:
    - pip
  imports:
    - keycloak
    - keycloak.authorization
  # commands:
  #  - pip check

about:
  home: https://github.com/marcospereirampj/python-keycloak
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: python-keycloak is a Python package providing access to the Keycloak API.

extra:
  recipe-maintainers:
    - edennuriel
    - fcollonval
