{% set name = "python-keycloak" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7d4de9a7bcd5802221aab55e852d1d9408a3f8da9c1f0a54e3fe4b050a306c97

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4
  run:
    - python >=3.6,<4
    - python-jose >=1.4.0
    - requests >=2.20.0
    - urllib3 >=1.26.0

test:
  requires:
    - pip
  imports:
    - keycloak
    - keycloak.authorization
  # commands:
  #  - pip check

about:
  home: https://github.com/marcospereirampj/python-keycloak
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: python-keycloak is a Python package providing access to the Keycloak API.

extra:
  recipe-maintainers:
    - edennuriel
    - fcollonval
