{% set name = "python-keycloak" %}
{% set version = "2.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2f22700b6ef8c167284a82c23736f6febc905bd0ab85981dca12171adf3667af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4
    - poetry-core >=1.0.0
  run:
    - deprecation >=2.1.0,<3.0.0
    - python >=3.7,<4
    - python-jose >=3.3.0,<4.0.0
    - requests >=2.28.2,<3.0.0
    - requests-toolbelt >=0.10.1,<1.0.0
    - urllib3 >=1.26.14,<2.0.0

test:
  requires:
    - pip
  imports:
    - keycloak
    - keycloak.authorization
  # commands:
  #  - pip check

about:
  home: https://github.com/marcospereirampj/python-keycloak
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: python-keycloak is a Python package providing access to the Keycloak API.

extra:
  recipe-maintainers:
    - edennuriel
    - fcollonval
