{% set name = "python-keycloak" %}
{% set version = "3.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_keycloak-{{ version }}.tar.gz
  sha256: f47b9d7aa137b6cb9133cc0eee158eabba54e9e40b9de6e5f44141a0458ae5a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - requests >=2.20.0
    - python-jose >=3.3.0
    - requests-toolbelt >=0.6.0
    - deprecation >=2.1.0

test:
  imports:
    - keycloak
    - keycloak.authorization
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marcospereirampj/python-keycloak
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: python-keycloak is a Python package providing access to the Keycloak API.

extra:
  recipe-maintainers:
    - jan-janssen
    - edennuriel
    - fcollonval
