{% set name = "python-keycloak" %}
{% set version = "0.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f3caddf2108f62cea6122243e33cb7e27bafbd7b8016be347de120ecf898b919

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4
  run:
    - python >=3.6,<4
    - python-jose >=1.4.0
    - requests >=2.20.0

test:
  requires:
    - pip
  imports:
    - keycloak
    - keycloak.authorization
    - keycloak.tests
  # commands:
  #  - pip check

about:
  home: https://github.com/marcospereirampj/python-keycloak
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: python-keycloak is a Python package providing access to the Keycloak API.

extra:
  recipe-maintainers:
    - edennuriel
    - fcollonval
