{% set name = "python-keycloak" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f13ad45d99449c34be5c94122fae00334bef7b672dfd1e222971e77e3aa2ea7a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4
    - poetry-core >=1.0.0
  run:
    - python >=3.7,<4
    - python-jose >=3.3.0
    - requests >=2.20.0
    - urllib3 >=1.26.0

test:
  requires:
    - pip
  imports:
    - keycloak
    - keycloak.authorization
  # commands:
  #  - pip check

about:
  home: https://github.com/marcospereirampj/python-keycloak
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: python-keycloak is a Python package providing access to the Keycloak API.

extra:
  recipe-maintainers:
    - edennuriel
    - fcollonval
