{% set name = "python-keycloak" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b71f85e7d5ccfe0dd679622949ea38026fdb7b74fdd8d4cb35ef21e3a756e583

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - python-jose >=1.4.0
    - requests >=2.20.0

test:
  imports:
    - keycloak
    - keycloak.authorization
    - keycloak.tests

about:
  home: https://github.com/marcospereirampj/python-keycloak
  license: MIT
  license_family: MIT
  # PR upstream to package license https://github.com/marcospereirampj/python-keycloak/pull/68
  license_file: LICENSE.txt
  summary: python-keycloak is a Python package providing access to the Keycloak API.

extra:
  recipe-maintainers:
    - edennuriel
